name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build murphy library
      run: ./gradlew :murphy:assembleRelease

    - name: Upload AAR
      uses: actions/upload-artifact@v3
      with:
        name: murphy-release
        path: murphy/build/outputs/aar/*.aar
